name: Backend CD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write .env file
        run: | 
            echo "${{ secrets.ENV_FILE }}" > .env
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PAT }}

      - name: Build and Push Docker Image
        run: |
          docker compose build
          docker compose push

      - name: Copy init.sql
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "init.sql"
          target: "/home/ubuntu/ds/backend"

      - name: Copy docker-compose
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "docker-compose.yaml"
          target: "/home/ubuntu/ds/backend"

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu/ds/backend
            echo "${{ secrets.ENV_FILE }}" > .env
            chmod 644 .env
            
            docker container prune
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d
            docker image prune -f
